version: "3"
services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
      args:
        VUE_APP_API_URL: "localhost:5000"
    ports:
      - "8000:8080"
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "5000:5000"
