[uwsgi]
module = wsgi:app

master = true
; processes = 4
processes = 1 ; With duckdb, multiple processes cause database lock issues
threads = 1

; socket = myproject.sock
; chmod-socket = 660
; vacuum = true

die-on-term = true