SANDPIPER_VERSION: '14_test'

KINGFISHER_METADATA_DATE: '20220616'
ACCESSIONS_FILE: '../test/data/6_runs/6_runs.accessions'

CONDENSED_OTU_TABLE: '../test/data/6_runs/6_runs.condensed.csv.gz'
OTU_TABLE: '../test/data/6_runs/6_runs.otu_table2.csv.gz'