SANDPIPER_VERSION: '19'

KINGFISHER_METADATA_DATE: '20220627'
ACCESSIONS_FILE: ../sra_metadata/sra_metadata_20220209.accessions

BIOPROJECT_METADATA_DATE: '20220711'

JSON_METADATA_FILES: '../sra_metadata/sra_metadata_20220209/*'

CONDENSED_OTU_TABLE: '~/m/msingle/mess/102_r207_renew_of_dec_2021_sras/sra102_r207.condense.with_header.csv.gz'
OTU_TABLE: '~/m/msingle/mess/102_r207_renew_of_dec_2021_sras/sra102_r207.otu_table.csv.gz'
HOST_OR_NOT_PREDICTION_GZ: '/home/woodcrob/m/big_data_microbiome/9_organism_prediction_r207/output/host_or_not_prediction/host_or_not_preds.csv.gz'

TEST_OR_PROD: 'prod'