SANDPIPER_VERSION: '25'

KINGFISHER_METADATA_DATE: '20220627'
ACCESSIONS_FILE: ../sra_metadata/sra_metadata_20220209.accessions

METAPACKAGE_DESCRIBE: 'metapackage_describe.csv'

BIOPROJECT_METADATA_DATE: '20220711'

JSON_METADATA_FILES: '../sra_metadata/sra_metadata_20220209/*'

# PROCESSING_DIRECTORY: '/work/microbiome/msingle/mess/174_R220_renew/processing_20240531'
CONDENSED_OTU_TABLE: '/work/microbiome/msingle/mess/174_R220_renew/processing_20240531/condensed.csv.gz'
OTU_TABLE: '/work/microbiome/msingle/mess/174_R220_renew/processing_20240531/otu_table.csv.gz'
HOST_OR_NOT_PREDICTION: '/work/microbiome/msingle/mess/174_R220_renew/processing_20240531/host_or_not_prediction/host_or_not_preds.csv'
SMF_FILE: '/work/microbiome/msingle/mess/174_R220_renew/processing_20240531/microbial_fractions.csv'

TEST_OR_PROD: 'prod'