SANDPIPER_VERSION: '18_test'

KINGFISHER_METADATA_DATE: '20220627'
ACCESSIONS_FILE: '../test/data/6_runs/accessions'

BIOPROJECT_METADATA_DATE: '20220711'

JSON_METADATA_FILES: '../test/data/6_runs/metadata_each_line.json'

# Output from ~/git/singlem-sra-processing
CONDENSED_OTU_TABLE: '../test/data/6_runs/condensed.csv.gz'
OTU_TABLE: '../test/data/6_runs/otu_table.csv.gz'
HOST_OR_NOT_PREDICTION_GZ: '../test/data/6_runs/host_or_not_preds.tsv.gz'
SMF_FILE: '../test/data/6_runs/smf.csv'

TEST_OR_PROD: 'test'